###############################################################
#  Generated by:      Cadence Innovus 21.15-s110_1
#  OS:                Linux x86_64(Host ID ic312.vit.ac.in)
#  Generated on:      Sat Mar  7 16:51:10 2026
#  Design:            alarm_clock_top
#  Command:           create_ccopt_clock_tree_spec -file clock_tree.spec
###############################################################
#-------------------------------------------------------------------------------
# Clock tree setup script - dialect: Innovus
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------

if { [get_ccopt_clock_trees] != {} } {
  error {Cannot run clock tree spec: clock trees are already defined.}
}

namespace eval ::ccopt {}
namespace eval ::ccopt::ilm {}
set ::ccopt::ilm::ccoptSpecRestoreData {}
# Start by checking for unflattened ILMs.
# Will flatten if so and then check the db sync.
if { [catch {ccopt_check_and_flatten_ilms_no_restore}] } {
  return -code error
}
# cache the value of the restore command output by the ILM flattening code
set ::ccopt::ilm::ccoptSpecRestoreData $::ccopt::ilm::ccoptRestoreILMState

# The following pins are clock sources
set_ccopt_property cts_is_sdc_clock_root -pin clk true

# Clocks present at pin clk
#   clk (period 10.000ns) in timing_config const([alarm_constraints_1.sdc])
create_ccopt_clock_tree -name clk -source clk -no_skew_group
# Clock period setting for source pin of clk
set_ccopt_property clock_period -pin clk 10

##############################################################################
##
## Timing connectivity based skew groups: off
##
##############################################################################
set_ccopt_property timing_connectivity_info {}

# Skew group to balance non generated clock:clk in timing_config:const (sdc alarm_constraints_1.sdc)
create_ccopt_skew_group -name clk/const -sources clk -auto_sinks
set_ccopt_property include_source_latency -skew_group clk/const true
set_ccopt_property extracted_from_clock_name -skew_group clk/const clk
set_ccopt_property extracted_from_constraint_mode_name -skew_group clk/const const
set_ccopt_property extracted_from_delay_corners -skew_group clk/const {max_delay min_delay}


check_ccopt_clock_tree_convergence
# Restore the ILM status if possible
if { [get_ccopt_property auto_design_state_for_ilms] == 0 } {
  if {$::ccopt::ilm::ccoptSpecRestoreData != {} } {
    eval $::ccopt::ilm::ccoptSpecRestoreData
  }
}

