
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Mar  1 2026 16:38:11 IST (Mar  1 2026 11:08:11 UTC)

// Verification Directory fv/alarm_clock_top 

module alarm_controller(clk, reset, alarm_enable, hour, min, sec,
     alarm_hour, alarm_min, alarm_sec, alarm_on);
  input clk, reset, alarm_enable;
  input [4:0] hour, alarm_hour;
  input [5:0] min, sec, alarm_min, alarm_sec;
  output alarm_on;
  wire clk, reset, alarm_enable;
  wire [4:0] hour, alarm_hour;
  wire [5:0] min, sec, alarm_min, alarm_sec;
  wire alarm_on;
  wire [1:0] state;
  wire [1:0] alarm_cnt;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59;
  DFFQX1 alarm_on_reg(.CK (clk), .D (n_58), .Q (alarm_on));
  NOR2XL g613__2398(.A (reset), .B (n_59), .Y (n_58));
  NAND2BX1 g614__5107(.AN (state[0]), .B (state[1]), .Y (n_59));
  DFFQX1 \alarm_cnt_reg[0] (.CK (clk), .D (n_55), .Q (alarm_cnt[0]));
  DFFQX1 \alarm_cnt_reg[1] (.CK (clk), .D (n_54), .Q (alarm_cnt[1]));
  DFFQX1 \state_reg[0] (.CK (clk), .D (n_57), .Q (state[0]));
  DFFQX1 \state_reg[1] (.CK (clk), .D (n_56), .Q (state[1]));
  NOR2XL g1693__6260(.A (reset), .B (n_52), .Y (n_57));
  NOR2XL g1694__4319(.A (reset), .B (n_53), .Y (n_56));
  NOR2XL g1695__8428(.A (reset), .B (n_51), .Y (n_55));
  NOR2XL g1696__5526(.A (reset), .B (n_50), .Y (n_54));
  MXI2XL g1697__6783(.A (state[1]), .B (n_32), .S0 (n_48), .Y (n_53));
  MXI2XL g1698__3680(.A (state[0]), .B (n_20), .S0 (n_48), .Y (n_52));
  MXI2XL g1699__1617(.A (alarm_cnt[0]), .B (n_21), .S0 (n_49), .Y
       (n_51));
  MXI2XL g1700__2802(.A (alarm_cnt[1]), .B (n_33), .S0 (n_49), .Y
       (n_50));
  OAI21X1 g1701__1705(.A0 (n_22), .A1 (n_59), .B0 (n_47), .Y (n_49));
  OAI211X1 g1702__5122(.A0 (state[0]), .A1 (n_37), .B0 (n_23), .C0
       (n_47), .Y (n_48));
  OAI211X1 g1703__8246(.A0 (alarm_min[4]), .A1 (n_17), .B0 (n_45), .C0
       (n_46), .Y (n_47));
  AOI211X1 g1704__7098(.A0 (alarm_min[5]), .A1 (n_11), .B0 (n_30), .C0
       (n_44), .Y (n_46));
  AOI211X1 g1705__6131(.A0 (hour[4]), .A1 (n_5), .B0 (n_29), .C0
       (n_42), .Y (n_45));
  OAI21X1 g1706__1881(.A0 (hour[4]), .A1 (n_5), .B0 (n_43), .Y (n_44));
  NOR4X1 g1707__5115(.A (n_20), .B (n_34), .C (n_24), .D (n_41), .Y
       (n_43));
  NAND4XL g1708__7482(.A (n_36), .B (n_35), .C (n_40), .D (n_39), .Y
       (n_42));
  OAI221X1 g1709__4733(.A0 (hour[2]), .A1 (n_10), .B0 (hour[3]), .B1
       (n_4), .C0 (n_38), .Y (n_41));
  AOI211X1 g1710__6161(.A0 (alarm_min[2]), .A1 (n_12), .B0 (n_27), .C0
       (n_28), .Y (n_40));
  AOI211X1 g1711__9315(.A0 (sec[1]), .A1 (n_8), .B0 (n_25), .C0 (n_26),
       .Y (n_39));
  AOI221X1 g1712__9945(.A0 (hour[2]), .A1 (n_10), .B0 (hour[3]), .B1
       (n_4), .C0 (n_31), .Y (n_38));
  AOI22X1 g1713__2883(.A0 (n_1), .A1 (n_21), .B0 (alarm_enable), .B1
       (n_0), .Y (n_37));
  AOI222XL g1714__2346(.A0 (min[2]), .A1 (n_16), .B0 (min[3]), .B1
       (n_9), .C0 (n_2), .C1 (alarm_min[3]), .Y (n_36));
  AOI222XL g1715__1666(.A0 (alarm_sec[1]), .A1 (n_6), .B0
       (alarm_sec[2]), .B1 (n_15), .C0 (n_3), .C1 (sec[2]), .Y (n_35));
  OAI22X1 g1716__7410(.A0 (alarm_hour[0]), .A1 (n_7), .B0
       (alarm_hour[1]), .B1 (n_19), .Y (n_34));
  OAI2BB1XL g1717__6417(.A0N (alarm_cnt[1]), .A1N (alarm_cnt[0]), .B0
       (state[1]), .Y (n_33));
  NAND2XL g1718__5477(.A (n_59), .B (n_20), .Y (n_32));
  OAI22X1 g1719__2398(.A0 (hour[0]), .A1 (n_14), .B0 (hour[1]), .B1
       (n_18), .Y (n_31));
  OAI22X1 g1720__5107(.A0 (alarm_min[5]), .A1 (n_11), .B0 (min[4]), .B1
       (n_13), .Y (n_30));
  CLKXOR2X1 g1721__6260(.A (min[0]), .B (alarm_min[0]), .Y (n_29));
  XOR2XL g1722__4319(.A (min[1]), .B (alarm_min[1]), .Y (n_28));
  XOR2XL g1723__8428(.A (sec[4]), .B (alarm_sec[4]), .Y (n_27));
  XOR2XL g1724__5526(.A (sec[5]), .B (alarm_sec[5]), .Y (n_26));
  XOR2XL g1725__6783(.A (sec[0]), .B (alarm_sec[0]), .Y (n_25));
  XOR2XL g1726__3680(.A (sec[3]), .B (alarm_sec[3]), .Y (n_24));
  NAND2XL g1727__1617(.A (state[0]), .B (state[1]), .Y (n_23));
  NOR2XL g1728__2802(.A (alarm_cnt[0]), .B (alarm_cnt[1]), .Y (n_22));
  NOR2XL g1729__1705(.A (alarm_cnt[0]), .B (n_59), .Y (n_21));
  NAND2XL g1730__5122(.A (state[0]), .B (n_0), .Y (n_20));
  INVXL g1731(.A (hour[1]), .Y (n_19));
  INVX1 g1732(.A (alarm_hour[1]), .Y (n_18));
  INVXL g1733(.A (min[4]), .Y (n_17));
  INVX1 g1734(.A (alarm_min[2]), .Y (n_16));
  INVX1 g1735(.A (sec[2]), .Y (n_15));
  INVX1 g1736(.A (alarm_hour[0]), .Y (n_14));
  INVX1 g1737(.A (alarm_min[4]), .Y (n_13));
  INVXL g1738(.A (min[2]), .Y (n_12));
  INVX1 g1739(.A (min[5]), .Y (n_11));
  CLKINVX1 g1743(.A (state[1]), .Y (n_0));
  INVX1 g1744(.A (alarm_hour[2]), .Y (n_10));
  INVX1 g1745(.A (alarm_min[3]), .Y (n_9));
  INVXL g1746(.A (alarm_sec[1]), .Y (n_8));
  INVXL g1747(.A (hour[0]), .Y (n_7));
  INVX1 g1748(.A (sec[1]), .Y (n_6));
  INVX1 g1749(.A (alarm_hour[4]), .Y (n_5));
  INVX1 g1750(.A (alarm_hour[3]), .Y (n_4));
  INVXL g1751(.A (alarm_sec[2]), .Y (n_3));
  INVXL g1752(.A (min[3]), .Y (n_2));
  INVX1 g1753(.A (alarm_cnt[1]), .Y (n_1));
endmodule

module alarm_register(clk, reset, alarm_set_sync, set_hour, set_min,
     set_sec, alarm_hour, alarm_min, alarm_sec, alarm_enable);
  input clk, reset, alarm_set_sync;
  input [4:0] set_hour;
  input [5:0] set_min, set_sec;
  output [4:0] alarm_hour;
  output [5:0] alarm_min, alarm_sec;
  output alarm_enable;
  wire clk, reset, alarm_set_sync;
  wire [4:0] set_hour;
  wire [5:0] set_min, set_sec;
  wire [4:0] alarm_hour;
  wire [5:0] alarm_min, alarm_sec;
  wire alarm_enable;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35;
  DFFQX1 \alarm_min_reg[4] (.CK (clk), .D (n_29), .Q (alarm_min[4]));
  DFFQX1 \alarm_hour_reg[3] (.CK (clk), .D (n_20), .Q (alarm_hour[3]));
  DFFQX1 \alarm_hour_reg[4] (.CK (clk), .D (n_34), .Q (alarm_hour[4]));
  DFFQX1 \alarm_sec_reg[5] (.CK (clk), .D (n_27), .Q (alarm_sec[5]));
  DFFQX1 \alarm_min_reg[0] (.CK (clk), .D (n_33), .Q (alarm_min[0]));
  DFFQX1 \alarm_min_reg[1] (.CK (clk), .D (n_32), .Q (alarm_min[1]));
  DFFQX1 \alarm_min_reg[2] (.CK (clk), .D (n_35), .Q (alarm_min[2]));
  DFFQX1 \alarm_min_reg[3] (.CK (clk), .D (n_30), .Q (alarm_min[3]));
  DFFQX1 \alarm_hour_reg[0] (.CK (clk), .D (n_31), .Q (alarm_hour[0]));
  SDFFQX1 alarm_enable_reg(.CK (clk), .D (n_0), .SI (alarm_enable), .SE
       (n_1), .Q (alarm_enable));
  DFFQX1 \alarm_min_reg[5] (.CK (clk), .D (n_28), .Q (alarm_min[5]));
  DFFQX1 \alarm_sec_reg[0] (.CK (clk), .D (n_19), .Q (alarm_sec[0]));
  DFFQX1 \alarm_sec_reg[1] (.CK (clk), .D (n_25), .Q (alarm_sec[1]));
  DFFQX1 \alarm_hour_reg[2] (.CK (clk), .D (n_24), .Q (alarm_hour[2]));
  DFFQX1 \alarm_sec_reg[2] (.CK (clk), .D (n_23), .Q (alarm_sec[2]));
  DFFQX1 \alarm_sec_reg[3] (.CK (clk), .D (n_22), .Q (alarm_sec[3]));
  DFFQX1 \alarm_sec_reg[4] (.CK (clk), .D (n_21), .Q (alarm_sec[4]));
  DFFQX1 \alarm_hour_reg[1] (.CK (clk), .D (n_26), .Q (alarm_hour[1]));
  NOR2XL g70__8246(.A (reset), .B (n_18), .Y (n_35));
  NOR2XL g71__7098(.A (reset), .B (n_14), .Y (n_34));
  NOR2XL g72__6131(.A (reset), .B (n_17), .Y (n_33));
  NOR2XL g73__1881(.A (reset), .B (n_15), .Y (n_32));
  NOR2XL g74__5115(.A (reset), .B (n_11), .Y (n_31));
  NOR2XL g75__7482(.A (reset), .B (n_13), .Y (n_30));
  NOR2XL g76__4733(.A (reset), .B (n_12), .Y (n_29));
  NOR2XL g77__6161(.A (reset), .B (n_9), .Y (n_28));
  NOR2XL g78__9315(.A (reset), .B (n_10), .Y (n_27));
  NOR2XL g79__9945(.A (reset), .B (n_2), .Y (n_26));
  NOR2XL g80__2883(.A (reset), .B (n_7), .Y (n_25));
  NOR2XL g81__2346(.A (reset), .B (n_5), .Y (n_24));
  NOR2XL g82__1666(.A (reset), .B (n_16), .Y (n_23));
  NOR2XL g83__7410(.A (reset), .B (n_4), .Y (n_22));
  NOR2XL g84__6417(.A (reset), .B (n_6), .Y (n_21));
  NOR2XL g85__5477(.A (reset), .B (n_3), .Y (n_20));
  NOR2XL g86__2398(.A (reset), .B (n_8), .Y (n_19));
  MXI2XL g87__5107(.A (alarm_min[2]), .B (set_min[2]), .S0
       (alarm_set_sync), .Y (n_18));
  MXI2XL g88__6260(.A (alarm_min[0]), .B (set_min[0]), .S0
       (alarm_set_sync), .Y (n_17));
  MXI2XL g89__4319(.A (alarm_sec[2]), .B (set_sec[2]), .S0
       (alarm_set_sync), .Y (n_16));
  MXI2XL g90__8428(.A (alarm_min[1]), .B (set_min[1]), .S0
       (alarm_set_sync), .Y (n_15));
  MXI2XL g91__5526(.A (alarm_hour[4]), .B (set_hour[4]), .S0
       (alarm_set_sync), .Y (n_14));
  MXI2XL g92__6783(.A (alarm_min[3]), .B (set_min[3]), .S0
       (alarm_set_sync), .Y (n_13));
  MXI2XL g93__3680(.A (alarm_min[4]), .B (set_min[4]), .S0
       (alarm_set_sync), .Y (n_12));
  MXI2XL g94__1617(.A (alarm_hour[0]), .B (set_hour[0]), .S0
       (alarm_set_sync), .Y (n_11));
  MXI2XL g95__2802(.A (alarm_sec[5]), .B (set_sec[5]), .S0
       (alarm_set_sync), .Y (n_10));
  MXI2XL g96__1705(.A (alarm_min[5]), .B (set_min[5]), .S0
       (alarm_set_sync), .Y (n_9));
  MXI2XL g97__5122(.A (alarm_sec[0]), .B (set_sec[0]), .S0
       (alarm_set_sync), .Y (n_8));
  MXI2XL g98__8246(.A (alarm_sec[1]), .B (set_sec[1]), .S0
       (alarm_set_sync), .Y (n_7));
  MXI2XL g99__7098(.A (alarm_sec[4]), .B (set_sec[4]), .S0
       (alarm_set_sync), .Y (n_6));
  MXI2XL g100__6131(.A (alarm_hour[2]), .B (set_hour[2]), .S0
       (alarm_set_sync), .Y (n_5));
  MXI2XL g101__1881(.A (alarm_sec[3]), .B (set_sec[3]), .S0
       (alarm_set_sync), .Y (n_4));
  MXI2XL g102__5115(.A (alarm_hour[3]), .B (set_hour[3]), .S0
       (alarm_set_sync), .Y (n_3));
  MXI2XL g103__7482(.A (alarm_hour[1]), .B (set_hour[1]), .S0
       (alarm_set_sync), .Y (n_2));
  NOR2XL g104__4733(.A (alarm_set_sync), .B (reset), .Y (n_1));
  CLKINVX1 g105(.A (reset), .Y (n_0));
endmodule

module time_counter(clk, reset, tick_1s, sec, min, hour);
  input clk, reset, tick_1s;
  output [5:0] sec, min;
  output [4:0] hour;
  wire clk, reset, tick_1s;
  wire [5:0] sec, min;
  wire [4:0] hour;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67;
  DFFQX1 \hour_reg[0] (.CK (clk), .D (n_51), .Q (hour[0]));
  DFFQX1 \hour_reg[1] (.CK (clk), .D (n_57), .Q (hour[1]));
  DFFQX1 \hour_reg[2] (.CK (clk), .D (n_61), .Q (hour[2]));
  DFFQX1 \hour_reg[3] (.CK (clk), .D (n_65), .Q (hour[3]));
  DFFQX1 \hour_reg[4] (.CK (clk), .D (n_67), .Q (hour[4]));
  DFFQX1 \min_reg[0] (.CK (clk), .D (n_33), .Q (min[0]));
  DFFQX1 \min_reg[1] (.CK (clk), .D (n_41), .Q (min[1]));
  DFFQX1 \min_reg[2] (.CK (clk), .D (n_48), .Q (min[2]));
  DFFQX1 \min_reg[3] (.CK (clk), .D (n_53), .Q (min[3]));
  DFFQX1 \min_reg[4] (.CK (clk), .D (n_52), .Q (min[4]));
  DFFQX1 \min_reg[5] (.CK (clk), .D (n_50), .Q (min[5]));
  DFFQX1 \sec_reg[0] (.CK (clk), .D (n_14), .Q (sec[0]));
  DFFQX1 \sec_reg[1] (.CK (clk), .D (n_22), .Q (sec[1]));
  DFFQX1 \sec_reg[2] (.CK (clk), .D (n_27), .Q (sec[2]));
  DFFQX1 \sec_reg[3] (.CK (clk), .D (n_31), .Q (sec[3]));
  DFFQX1 \sec_reg[4] (.CK (clk), .D (n_32), .Q (sec[4]));
  DFFQX1 \sec_reg[5] (.CK (clk), .D (n_29), .Q (sec[5]));
  INVXL g1763(.A (n_66), .Y (n_67));
  AOI32X1 g1764__6161(.A0 (n_3), .A1 (hour[4]), .A2 (n_58), .B0 (n_63),
       .B1 (hour[3]), .Y (n_66));
  OAI22XL g1765__9315(.A0 (hour[3]), .A1 (n_64), .B0 (n_62), .B1
       (reset), .Y (n_65));
  INVX1 g1767(.A (n_63), .Y (n_64));
  NOR3X1 g1768__9945(.A (reset), .B (hour[4]), .C (n_58), .Y (n_63));
  NAND2XL g1769__2883(.A (hour[3]), .B (n_58), .Y (n_62));
  NOR2XL g1770__2346(.A (reset), .B (n_60), .Y (n_61));
  AOI21XL g1772__1666(.A0 (hour[2]), .A1 (n_55), .B0 (n_59), .Y (n_60));
  NOR2XL g1773__7410(.A (hour[2]), .B (n_55), .Y (n_59));
  NOR2XL g1774__6417(.A (reset), .B (n_56), .Y (n_57));
  NAND2BX1 g1775__5477(.AN (n_55), .B (hour[2]), .Y (n_58));
  AOI21XL g1778__2398(.A0 (hour[1]), .A1 (n_43), .B0 (n_54), .Y (n_56));
  NOR2XL g1781__5107(.A (hour[1]), .B (n_43), .Y (n_54));
  NAND2BX1 g1782__6260(.AN (n_43), .B (hour[1]), .Y (n_55));
  OAI32X1 g1784__4319(.A0 (n_6), .A1 (min[3]), .A2 (n_37), .B0 (reset),
       .B1 (n_46), .Y (n_53));
  NAND2XL g1785__8428(.A (n_49), .B (n_38), .Y (n_52));
  NOR2XL g1786__5526(.A (reset), .B (n_45), .Y (n_51));
  OAI32X1 g1787__6783(.A0 (n_6), .A1 (min[5]), .A2 (n_44), .B0 (reset),
       .B1 (n_47), .Y (n_50));
  OAI211X1 g1788__3680(.A0 (n_2), .A1 (n_40), .B0 (n_3), .C0 (min[4]),
       .Y (n_49));
  OAI32X1 g1789__1617(.A0 (reset), .A1 (min[2]), .A2 (n_42), .B0 (n_6),
       .B1 (n_35), .Y (n_48));
  NAND2XL g1790__2802(.A (min[5]), .B (n_44), .Y (n_47));
  OAI21X1 g1791__1705(.A0 (n_8), .A1 (n_40), .B0 (min[3]), .Y (n_46));
  XNOR2XL g1792__5122(.A (hour[0]), .B (n_39), .Y (n_45));
  NAND3X1 g1794__8246(.A (min[3]), .B (min[4]), .C (n_35), .Y (n_44));
  NAND2XL g1795__7098(.A (hour[0]), .B (n_39), .Y (n_43));
  NAND2XL g1796__6131(.A (n_12), .B (n_35), .Y (n_42));
  NOR2XL g1797__1881(.A (reset), .B (n_36), .Y (n_41));
  OR4XL g1798__5115(.A (n_6), .B (min[4]), .C (n_2), .D (n_37), .Y
       (n_38));
  OAI21X1 g1799__7482(.A0 (min[2]), .A1 (min[5]), .B0 (n_35), .Y
       (n_40));
  NOR3X1 g1800__4733(.A (min[2]), .B (n_12), .C (n_37), .Y (n_39));
  CLKINVX1 g1801(.A (n_35), .Y (n_37));
  AOI21XL g1804__6161(.A0 (min[1]), .A1 (n_25), .B0 (n_34), .Y (n_36));
  NOR2XL g1806__9315(.A (min[1]), .B (n_25), .Y (n_34));
  NOR2BX1 g1808__9945(.AN (min[1]), .B (n_25), .Y (n_35));
  NOR2XL g1809__2883(.A (reset), .B (n_26), .Y (n_33));
  NAND2XL g1810__2346(.A (n_30), .B (n_19), .Y (n_32));
  OAI32X1 g1811__1666(.A0 (n_5), .A1 (sec[3]), .A2 (n_16), .B0 (reset),
       .B1 (n_28), .Y (n_31));
  OAI211X1 g1813__7410(.A0 (n_4), .A1 (n_21), .B0 (n_3), .C0 (sec[4]),
       .Y (n_30));
  OAI32X1 g1814__6417(.A0 (reset), .A1 (n_1), .A2 (n_23), .B0 (n_24),
       .B1 (sec[5]), .Y (n_29));
  OAI21X1 g1815__5477(.A0 (n_9), .A1 (n_21), .B0 (sec[3]), .Y (n_28));
  OAI32X1 g1816__2398(.A0 (reset), .A1 (n_16), .A2 (n_0), .B0 (n_5),
       .B1 (n_18), .Y (n_27));
  XNOR2XL g1817__5107(.A (min[0]), .B (n_20), .Y (n_26));
  NAND2BX1 g1819__6260(.AN (n_5), .B (n_23), .Y (n_24));
  NAND2XL g1820__4319(.A (min[0]), .B (n_20), .Y (n_25));
  NOR2XL g1821__8428(.A (reset), .B (n_17), .Y (n_22));
  NOR2XL g1822__5526(.A (n_10), .B (n_16), .Y (n_23));
  OR4XL g1823__6783(.A (n_5), .B (sec[4]), .C (n_4), .D (n_16), .Y
       (n_19));
  OAI21X1 g1824__3680(.A0 (sec[2]), .A1 (sec[5]), .B0 (n_18), .Y
       (n_21));
  NOR3X1 g1825__1617(.A (sec[2]), .B (n_16), .C (n_13), .Y (n_20));
  INVX1 g1826(.A (n_16), .Y (n_18));
  AOI21XL g1828__2802(.A0 (sec[1]), .A1 (n_7), .B0 (n_15), .Y (n_17));
  NAND2BX1 g1829__1705(.AN (n_7), .B (sec[1]), .Y (n_16));
  NOR2XL g1830__5122(.A (sec[1]), .B (n_7), .Y (n_15));
  NOR2XL g1831__8246(.A (reset), .B (n_11), .Y (n_14));
  NAND2BX1 g1833__7098(.AN (n_10), .B (sec[5]), .Y (n_13));
  XNOR2XL g1834__6131(.A (tick_1s), .B (sec[0]), .Y (n_11));
  NAND3X1 g1835__1881(.A (min[3]), .B (min[5]), .C (min[4]), .Y (n_12));
  NOR2XL g1836__5115(.A (sec[2]), .B (sec[4]), .Y (n_9));
  NOR2XL g1837__7482(.A (min[2]), .B (min[4]), .Y (n_8));
  NAND2XL g1838__4733(.A (sec[3]), .B (sec[4]), .Y (n_10));
  NAND2XL g1839__6161(.A (tick_1s), .B (sec[0]), .Y (n_7));
  NAND2XL g1840__9315(.A (n_3), .B (min[2]), .Y (n_6));
  NAND2XL g1841__9945(.A (n_3), .B (sec[2]), .Y (n_5));
  INVX1 g1853(.A (sec[3]), .Y (n_4));
  CLKINVX1 g1862(.A (min[3]), .Y (n_2));
  CLKINVX1 g1863(.A (reset), .Y (n_3));
  INVX1 g1874(.A (sec[5]), .Y (n_1));
  NAND2BX1 g2__2883(.AN (sec[2]), .B (n_13), .Y (n_0));
endmodule

module time_generator(clk, reset, tick_1s);
  input clk, reset;
  output tick_1s;
  wire clk, reset;
  wire tick_1s;
  wire [25:0] div_cnt;
  wire inc_add_20_32_n_0, inc_add_20_32_n_1, inc_add_20_32_n_2,
       inc_add_20_32_n_3, inc_add_20_32_n_4, inc_add_20_32_n_5,
       inc_add_20_32_n_7, inc_add_20_32_n_8;
  wire inc_add_20_32_n_9, inc_add_20_32_n_10, inc_add_20_32_n_11,
       inc_add_20_32_n_12, inc_add_20_32_n_13, inc_add_20_32_n_15,
       inc_add_20_32_n_16, inc_add_20_32_n_17;
  wire inc_add_20_32_n_18, inc_add_20_32_n_20, inc_add_20_32_n_21,
       inc_add_20_32_n_22, inc_add_20_32_n_23, inc_add_20_32_n_26,
       inc_add_20_32_n_27, inc_add_20_32_n_28;
  wire inc_add_20_32_n_30, inc_add_20_32_n_32, inc_add_20_32_n_33,
       inc_add_20_32_n_34, inc_add_20_32_n_35, inc_add_20_32_n_39,
       inc_add_20_32_n_40, inc_add_20_32_n_41;
  wire inc_add_20_32_n_42, inc_add_20_32_n_43, inc_add_20_32_n_48,
       inc_add_20_32_n_49, inc_add_20_32_n_52, inc_add_20_32_n_54,
       inc_add_20_32_n_55, inc_add_20_32_n_56;
  wire inc_add_20_32_n_60, inc_add_20_32_n_62, inc_add_20_32_n_64,
       inc_add_20_32_n_66, inc_add_20_32_n_68, n_0, n_1, n_2;
  wire n_3, n_4, n_5, n_6, n_7, n_8, n_9, n_10;
  wire n_11, n_12, n_14, n_15, n_16, n_17, n_18, n_19;
  wire n_21, n_22, n_23, n_24, n_25, n_26, n_27, n_28;
  wire n_29, n_30, n_31, n_32, n_33, n_34, n_35, n_36;
  wire n_37, n_38, n_39, n_40, n_41, n_42, n_43, n_44;
  wire n_46, n_47, n_48, n_49, n_50, n_51, n_53, n_54;
  wire n_55, n_56, n_57, n_58, n_59, n_60, n_61, n_62;
  wire n_97, n_98;
  DFFQX1 tick_1s_reg(.CK (clk), .D (n_26), .Q (tick_1s));
  AO21X1 g951__2346(.A0 (div_cnt[1]), .A1 (n_36), .B0 (reset), .Y
       (n_62));
  NOR2XL g952__1666(.A (div_cnt[2]), .B (n_35), .Y (n_36));
  NAND4BXL g953__7410(.AN (div_cnt[4]), .B (div_cnt[3]), .C (n_31), .D
       (n_34), .Y (n_35));
  NOR4BX1 g954__6417(.AN (n_33), .B (div_cnt[0]), .C (div_cnt[9]), .D
       (n_29), .Y (n_34));
  NOR3X1 g955__5477(.A (div_cnt[23]), .B (div_cnt[20]), .C (n_32), .Y
       (n_33));
  NAND3X1 g956__2398(.A (n_27), .B (n_30), .C (n_28), .Y (n_32));
  NOR4X1 g957__5107(.A (div_cnt[8]), .B (div_cnt[7]), .C (div_cnt[6]),
       .D (div_cnt[5]), .Y (n_31));
  NOR4X1 g958__6260(.A (div_cnt[25]), .B (div_cnt[24]), .C
       (div_cnt[17]), .D (div_cnt[16]), .Y (n_30));
  OR4XL g959__4319(.A (div_cnt[19]), .B (div_cnt[22]), .C
       (div_cnt[18]), .D (div_cnt[21]), .Y (n_29));
  NOR4X1 g960__8428(.A (div_cnt[15]), .B (div_cnt[14]), .C
       (div_cnt[13]), .D (div_cnt[12]), .Y (n_28));
  NOR2XL g961__5526(.A (div_cnt[11]), .B (div_cnt[10]), .Y (n_27));
  NOR2BXL g2__6783(.AN (n_62), .B (reset), .Y (n_26));
  DFFQX1 \div_cnt_reg[10] (.CK (clk), .D (n_19), .Q (div_cnt[10]));
  DFFQX1 \div_cnt_reg[5] (.CK (clk), .D (n_22), .Q (div_cnt[5]));
  DFFQX1 \div_cnt_reg[6] (.CK (clk), .D (n_25), .Q (div_cnt[6]));
  DFFQX1 \div_cnt_reg[7] (.CK (clk), .D (n_24), .Q (div_cnt[7]));
  DFFQX1 \div_cnt_reg[8] (.CK (clk), .D (n_21), .Q (div_cnt[8]));
  DFFQX1 \div_cnt_reg[9] (.CK (clk), .D (n_97), .Q (div_cnt[9]));
  DFFQX1 \div_cnt_reg[4] (.CK (clk), .D (n_7), .Q (div_cnt[4]));
  DFFQX1 \div_cnt_reg[11] (.CK (clk), .D (n_18), .Q (div_cnt[11]));
  DFFQX1 \div_cnt_reg[12] (.CK (clk), .D (n_23), .Q (div_cnt[12]));
  DFFQX1 \div_cnt_reg[13] (.CK (clk), .D (n_16), .Q (div_cnt[13]));
  DFFQX1 \div_cnt_reg[14] (.CK (clk), .D (n_15), .Q (div_cnt[14]));
  DFFQX1 \div_cnt_reg[15] (.CK (clk), .D (n_14), .Q (div_cnt[15]));
  DFFQX1 \div_cnt_reg[0] (.CK (clk), .D (n_0), .Q (div_cnt[0]));
  DFFQX1 \div_cnt_reg[16] (.CK (clk), .D (n_98), .Q (div_cnt[16]));
  DFFQX1 \div_cnt_reg[17] (.CK (clk), .D (n_12), .Q (div_cnt[17]));
  DFFQX1 \div_cnt_reg[18] (.CK (clk), .D (n_11), .Q (div_cnt[18]));
  DFFQX1 \div_cnt_reg[19] (.CK (clk), .D (n_10), .Q (div_cnt[19]));
  DFFQX1 \div_cnt_reg[1] (.CK (clk), .D (n_3), .Q (div_cnt[1]));
  DFFQX1 \div_cnt_reg[20] (.CK (clk), .D (n_9), .Q (div_cnt[20]));
  DFFQX1 \div_cnt_reg[21] (.CK (clk), .D (n_8), .Q (div_cnt[21]));
  DFFQX1 \div_cnt_reg[22] (.CK (clk), .D (n_6), .Q (div_cnt[22]));
  DFFQX1 \div_cnt_reg[23] (.CK (clk), .D (n_5), .Q (div_cnt[23]));
  DFFQX1 \div_cnt_reg[24] (.CK (clk), .D (n_17), .Q (div_cnt[24]));
  DFFQX1 \div_cnt_reg[25] (.CK (clk), .D (n_4), .Q (div_cnt[25]));
  DFFQX1 \div_cnt_reg[2] (.CK (clk), .D (n_2), .Q (div_cnt[2]));
  DFFQX1 \div_cnt_reg[3] (.CK (clk), .D (n_1), .Q (div_cnt[3]));
  NOR2BXL g720__3680(.AN (n_42), .B (n_62), .Y (n_25));
  NOR2BXL g721__1617(.AN (n_43), .B (n_62), .Y (n_24));
  NOR2BXL g722__2802(.AN (n_48), .B (n_62), .Y (n_23));
  NOR2BXL g723__1705(.AN (n_41), .B (n_62), .Y (n_22));
  NOR2BXL g724__5122(.AN (n_44), .B (n_62), .Y (n_21));
  NOR2BXL g726__7098(.AN (n_46), .B (n_62), .Y (n_19));
  NOR2BX1 g727__6131(.AN (n_47), .B (n_62), .Y (n_18));
  NOR2BX1 g728__1881(.AN (n_60), .B (n_62), .Y (n_17));
  NOR2BXL g729__5115(.AN (n_49), .B (n_62), .Y (n_16));
  NOR2BX1 g730__7482(.AN (n_50), .B (n_62), .Y (n_15));
  NOR2BX1 g731__4733(.AN (n_51), .B (n_62), .Y (n_14));
  NOR2BXL g733__9315(.AN (n_53), .B (n_62), .Y (n_12));
  NOR2BX1 g734__9945(.AN (n_54), .B (n_62), .Y (n_11));
  NOR2BX1 g735__2883(.AN (n_55), .B (n_62), .Y (n_10));
  NOR2BXL g736__2346(.AN (n_56), .B (n_62), .Y (n_9));
  NOR2BX1 g737__1666(.AN (n_57), .B (n_62), .Y (n_8));
  NOR2BXL g738__7410(.AN (n_40), .B (n_62), .Y (n_7));
  NOR2BX1 g739__6417(.AN (n_58), .B (n_62), .Y (n_6));
  NOR2BX1 g740__5477(.AN (n_59), .B (n_62), .Y (n_5));
  NOR2BX1 g741__2398(.AN (n_61), .B (n_62), .Y (n_4));
  NOR2BXL g742__5107(.AN (n_37), .B (n_62), .Y (n_3));
  NOR2BXL g743__6260(.AN (n_38), .B (n_62), .Y (n_2));
  NOR2BXL g744__4319(.AN (n_39), .B (n_62), .Y (n_1));
  NOR2XL g745__8428(.A (div_cnt[0]), .B (n_62), .Y (n_0));
  OAI21X1 inc_add_20_32_g393__5526(.A0 (div_cnt[19]), .A1
       (inc_add_20_32_n_64), .B0 (inc_add_20_32_n_68), .Y (n_55));
  NAND2XL inc_add_20_32_g394__6783(.A (div_cnt[19]), .B
       (inc_add_20_32_n_64), .Y (inc_add_20_32_n_68));
  OAI21X1 inc_add_20_32_g395__3680(.A0 (div_cnt[11]), .A1
       (inc_add_20_32_n_54), .B0 (inc_add_20_32_n_66), .Y (n_47));
  NAND2XL inc_add_20_32_g396__1617(.A (div_cnt[11]), .B
       (inc_add_20_32_n_54), .Y (inc_add_20_32_n_66));
  OA21XL inc_add_20_32_g397__2802(.A0 (div_cnt[18]), .A1
       (inc_add_20_32_n_62), .B0 (inc_add_20_32_n_64), .Y (n_54));
  NAND2XL inc_add_20_32_g398__1705(.A (div_cnt[18]), .B
       (inc_add_20_32_n_62), .Y (inc_add_20_32_n_64));
  OAI21X1 inc_add_20_32_g399__5122(.A0 (div_cnt[23]), .A1
       (inc_add_20_32_n_48), .B0 (inc_add_20_32_n_60), .Y (n_59));
  ADDHX1 inc_add_20_32_g400__8246(.A (div_cnt[17]), .B
       (inc_add_20_32_n_35), .CO (inc_add_20_32_n_62), .S (n_53));
  NAND2XL inc_add_20_32_g401__7098(.A (div_cnt[23]), .B
       (inc_add_20_32_n_48), .Y (inc_add_20_32_n_60));
  OA21XL inc_add_20_32_g402__6131(.A0 (div_cnt[10]), .A1
       (inc_add_20_32_n_41), .B0 (inc_add_20_32_n_54), .Y (n_46));
  OAI21X1 inc_add_20_32_g403__1881(.A0 (div_cnt[21]), .A1
       (inc_add_20_32_n_42), .B0 (inc_add_20_32_n_55), .Y (n_57));
  OAI21X1 inc_add_20_32_g404__5115(.A0 (div_cnt[25]), .A1
       (inc_add_20_32_n_43), .B0 (inc_add_20_32_n_56), .Y (n_61));
  NAND2XL inc_add_20_32_g405__7482(.A (div_cnt[25]), .B
       (inc_add_20_32_n_43), .Y (inc_add_20_32_n_56));
  NAND2XL inc_add_20_32_g406__4733(.A (div_cnt[21]), .B
       (inc_add_20_32_n_42), .Y (inc_add_20_32_n_55));
  NAND2XL inc_add_20_32_g407__6161(.A (div_cnt[10]), .B
       (inc_add_20_32_n_41), .Y (inc_add_20_32_n_54));
  OAI21X1 inc_add_20_32_g408__9315(.A0 (div_cnt[15]), .A1
       (inc_add_20_32_n_34), .B0 (inc_add_20_32_n_52), .Y (n_51));
  NAND2XL inc_add_20_32_g409__9945(.A (div_cnt[15]), .B
       (inc_add_20_32_n_34), .Y (inc_add_20_32_n_52));
  OA21XL inc_add_20_32_g410__2883(.A0 (div_cnt[22]), .A1
       (inc_add_20_32_n_39), .B0 (inc_add_20_32_n_48), .Y (n_58));
  OAI21X1 inc_add_20_32_g411__2346(.A0 (div_cnt[13]), .A1
       (inc_add_20_32_n_26), .B0 (inc_add_20_32_n_49), .Y (n_49));
  NAND2XL inc_add_20_32_g412__1666(.A (div_cnt[13]), .B
       (inc_add_20_32_n_26), .Y (inc_add_20_32_n_49));
  NAND2XL inc_add_20_32_g413__7410(.A (div_cnt[22]), .B
       (inc_add_20_32_n_39), .Y (inc_add_20_32_n_48));
  OA21XL inc_add_20_32_g414__6417(.A0 (div_cnt[20]), .A1
       (inc_add_20_32_n_32), .B0 (inc_add_20_32_n_42), .Y (n_56));
  OA21XL inc_add_20_32_g415__5477(.A0 (div_cnt[24]), .A1
       (inc_add_20_32_n_30), .B0 (inc_add_20_32_n_43), .Y (n_60));
  OAI21X1 inc_add_20_32_g417__5107(.A0 (div_cnt[7]), .A1
       (inc_add_20_32_n_21), .B0 (inc_add_20_32_n_40), .Y (n_43));
  NAND2XL inc_add_20_32_g418__6260(.A (div_cnt[24]), .B
       (inc_add_20_32_n_30), .Y (inc_add_20_32_n_43));
  NAND2XL inc_add_20_32_g419__4319(.A (div_cnt[20]), .B
       (inc_add_20_32_n_32), .Y (inc_add_20_32_n_42));
  NOR2XL inc_add_20_32_g420__8428(.A (inc_add_20_32_n_1), .B
       (inc_add_20_32_n_22), .Y (inc_add_20_32_n_41));
  NAND2XL inc_add_20_32_g421__5526(.A (div_cnt[7]), .B
       (inc_add_20_32_n_21), .Y (inc_add_20_32_n_40));
  NOR2BX1 inc_add_20_32_g422__6783(.AN (inc_add_20_32_n_32), .B
       (inc_add_20_32_n_4), .Y (inc_add_20_32_n_39));
  OA21XL inc_add_20_32_g423__3680(.A0 (div_cnt[14]), .A1
       (inc_add_20_32_n_27), .B0 (inc_add_20_32_n_34), .Y (n_50));
  OAI21X1 inc_add_20_32_g425__2802(.A0 (div_cnt[5]), .A1
       (inc_add_20_32_n_17), .B0 (inc_add_20_32_n_33), .Y (n_41));
  NOR2XL inc_add_20_32_g426__1705(.A (inc_add_20_32_n_0), .B
       (inc_add_20_32_n_23), .Y (inc_add_20_32_n_35));
  NAND2XL inc_add_20_32_g427__5122(.A (div_cnt[14]), .B
       (inc_add_20_32_n_27), .Y (inc_add_20_32_n_34));
  NAND2XL inc_add_20_32_g428__8246(.A (div_cnt[5]), .B
       (inc_add_20_32_n_17), .Y (inc_add_20_32_n_33));
  NOR2XL inc_add_20_32_g429__7098(.A (inc_add_20_32_n_8), .B
       (inc_add_20_32_n_23), .Y (inc_add_20_32_n_32));
  OA21XL inc_add_20_32_g430__6131(.A0 (div_cnt[12]), .A1
       (inc_add_20_32_n_20), .B0 (inc_add_20_32_n_26), .Y (n_48));
  NOR2XL inc_add_20_32_g431__1881(.A (inc_add_20_32_n_18), .B
       (inc_add_20_32_n_23), .Y (inc_add_20_32_n_30));
  OAI21X1 inc_add_20_32_g432__5115(.A0 (div_cnt[3]), .A1
       (inc_add_20_32_n_12), .B0 (inc_add_20_32_n_28), .Y (n_39));
  NAND2XL inc_add_20_32_g433__7482(.A (div_cnt[3]), .B
       (inc_add_20_32_n_12), .Y (inc_add_20_32_n_28));
  NOR2BX1 inc_add_20_32_g434__4733(.AN (inc_add_20_32_n_20), .B
       (inc_add_20_32_n_2), .Y (inc_add_20_32_n_27));
  NAND2XL inc_add_20_32_g435__6161(.A (div_cnt[12]), .B
       (inc_add_20_32_n_20), .Y (inc_add_20_32_n_26));
  OA21XL inc_add_20_32_g436__9315(.A0 (div_cnt[8]), .A1
       (inc_add_20_32_n_15), .B0 (inc_add_20_32_n_22), .Y (n_44));
  OA21XL inc_add_20_32_g437__9945(.A0 (div_cnt[6]), .A1
       (inc_add_20_32_n_16), .B0 (inc_add_20_32_n_21), .Y (n_42));
  NAND4XL inc_add_20_32_g438__2883(.A (div_cnt[15]), .B (div_cnt[14]),
       .C (inc_add_20_32_n_11), .D (inc_add_20_32_n_15), .Y
       (inc_add_20_32_n_23));
  NAND2XL inc_add_20_32_g439__2346(.A (div_cnt[8]), .B
       (inc_add_20_32_n_15), .Y (inc_add_20_32_n_22));
  NAND2XL inc_add_20_32_g440__1666(.A (div_cnt[6]), .B
       (inc_add_20_32_n_16), .Y (inc_add_20_32_n_21));
  NOR2BX1 inc_add_20_32_g441__7410(.AN (inc_add_20_32_n_15), .B
       (inc_add_20_32_n_7), .Y (inc_add_20_32_n_20));
  OA21XL inc_add_20_32_g442__6417(.A0 (div_cnt[4]), .A1
       (inc_add_20_32_n_9), .B0 (inc_add_20_32_n_17), .Y (n_40));
  NAND3X1 inc_add_20_32_g443__5477(.A (div_cnt[22]), .B (div_cnt[23]),
       .C (inc_add_20_32_n_13), .Y (inc_add_20_32_n_18));
  NAND2XL inc_add_20_32_g444__2398(.A (div_cnt[4]), .B
       (inc_add_20_32_n_9), .Y (inc_add_20_32_n_17));
  NOR2XL inc_add_20_32_g445__5107(.A (inc_add_20_32_n_5), .B
       (inc_add_20_32_n_10), .Y (inc_add_20_32_n_16));
  NOR4BBX1 inc_add_20_32_g446__6260(.AN (div_cnt[7]), .BN (div_cnt[6]),
       .C (inc_add_20_32_n_5), .D (inc_add_20_32_n_10), .Y
       (inc_add_20_32_n_15));
  OA21XL inc_add_20_32_g447__4319(.A0 (div_cnt[2]), .A1
       (inc_add_20_32_n_3), .B0 (inc_add_20_32_n_12), .Y (n_38));
  NOR2XL inc_add_20_32_g448__8428(.A (inc_add_20_32_n_4), .B
       (inc_add_20_32_n_8), .Y (inc_add_20_32_n_13));
  NAND2XL inc_add_20_32_g449__5526(.A (div_cnt[2]), .B
       (inc_add_20_32_n_3), .Y (inc_add_20_32_n_12));
  NOR2XL inc_add_20_32_g450__6783(.A (inc_add_20_32_n_2), .B
       (inc_add_20_32_n_7), .Y (inc_add_20_32_n_11));
  CLKINVX1 inc_add_20_32_g451(.A (inc_add_20_32_n_10), .Y
       (inc_add_20_32_n_9));
  NAND3X1 inc_add_20_32_g452__3680(.A (div_cnt[2]), .B (div_cnt[3]), .C
       (inc_add_20_32_n_3), .Y (inc_add_20_32_n_10));
  NAND4XL inc_add_20_32_g453__1617(.A (div_cnt[17]), .B (div_cnt[19]),
       .C (div_cnt[16]), .D (div_cnt[18]), .Y (inc_add_20_32_n_8));
  NAND4XL inc_add_20_32_g454__2802(.A (div_cnt[9]), .B (div_cnt[11]),
       .C (div_cnt[8]), .D (div_cnt[10]), .Y (inc_add_20_32_n_7));
  AOI2BB1X1 inc_add_20_32_g455__1705(.A0N (div_cnt[1]), .A1N
       (div_cnt[0]), .B0 (inc_add_20_32_n_3), .Y (n_37));
  NAND2XL inc_add_20_32_g456__5122(.A (div_cnt[5]), .B (div_cnt[4]), .Y
       (inc_add_20_32_n_5));
  NAND2XL inc_add_20_32_g457__8246(.A (div_cnt[21]), .B (div_cnt[20]),
       .Y (inc_add_20_32_n_4));
  AND2X1 inc_add_20_32_g458__7098(.A (div_cnt[0]), .B (div_cnt[1]), .Y
       (inc_add_20_32_n_3));
  NAND2XL inc_add_20_32_g459__6131(.A (div_cnt[13]), .B (div_cnt[12]),
       .Y (inc_add_20_32_n_2));
  CLKINVX1 inc_add_20_32_g460(.A (div_cnt[9]), .Y (inc_add_20_32_n_1));
  CLKINVX1 inc_add_20_32_g461(.A (div_cnt[16]), .Y (inc_add_20_32_n_0));
  AOI211X1 g2(.A0 (inc_add_20_32_n_1), .A1 (inc_add_20_32_n_22), .B0
       (inc_add_20_32_n_41), .C0 (n_62), .Y (n_97));
  AOI211X1 g962(.A0 (inc_add_20_32_n_0), .A1 (inc_add_20_32_n_23), .B0
       (inc_add_20_32_n_35), .C0 (n_62), .Y (n_98));
endmodule

module alarm_clock_top(clk, reset, alarm_set, set_hour, set_min,
     set_sec, hour, min, sec, alarm_hour, alarm_min, alarm_sec,
     alarm_on);
  input clk, reset, alarm_set;
  input [4:0] set_hour;
  input [5:0] set_min, set_sec;
  output [4:0] hour, alarm_hour;
  output [5:0] min, sec, alarm_min, alarm_sec;
  output alarm_on;
  wire clk, reset, alarm_set;
  wire [4:0] set_hour;
  wire [5:0] set_min, set_sec;
  wire [4:0] hour, alarm_hour;
  wire [5:0] min, sec, alarm_min, alarm_sec;
  wire alarm_on;
  wire alarm_enable, alarm_set_sync, tick_1s;
  alarm_controller ac(.clk (clk), .reset (reset), .alarm_enable
       (alarm_enable), .hour (hour), .min (min), .sec (sec),
       .alarm_hour (alarm_hour), .alarm_min (alarm_min), .alarm_sec
       (alarm_sec), .alarm_on (alarm_on));
  alarm_register ar(.clk (clk), .reset (reset), .alarm_set_sync
       (alarm_set_sync), .set_hour (set_hour), .set_min (set_min),
       .set_sec (set_sec), .alarm_hour (alarm_hour), .alarm_min
       (alarm_min), .alarm_sec (alarm_sec), .alarm_enable
       (alarm_enable));
  key_register kr(.clk (clk), .reset (reset), .alarm_set (alarm_set),
       .alarm_set_sync (alarm_set_sync));
  time_counter tc(.clk (clk), .reset (reset), .tick_1s (tick_1s), .sec
       (sec), .min (min), .hour (hour));
  time_generator tg(.clk (clk), .reset (reset), .tick_1s (tick_1s));
endmodule

