# ####################################################################

#  Created by Genus(TM) Synthesis Solution 21.14-s082_1 on Sun Mar 01 16:38:11 IST 2026

# ####################################################################

set sdc_version 2.0

set_units -capacitance 1000fF
set_units -time 1000ps

# Set the current design
current_design alarm_clock_top

create_clock -name "clk" -period 10.0 -waveform {0.0 5.0} [get_ports clk]
set_load -pin_load 0.05 [get_ports {hour[4]}]
set_load -pin_load 0.05 [get_ports {hour[3]}]
set_load -pin_load 0.05 [get_ports {hour[2]}]
set_load -pin_load 0.05 [get_ports {hour[1]}]
set_load -pin_load 0.05 [get_ports {hour[0]}]
set_load -pin_load 0.05 [get_ports {min[5]}]
set_load -pin_load 0.05 [get_ports {min[4]}]
set_load -pin_load 0.05 [get_ports {min[3]}]
set_load -pin_load 0.05 [get_ports {min[2]}]
set_load -pin_load 0.05 [get_ports {min[1]}]
set_load -pin_load 0.05 [get_ports {min[0]}]
set_load -pin_load 0.05 [get_ports {sec[5]}]
set_load -pin_load 0.05 [get_ports {sec[4]}]
set_load -pin_load 0.05 [get_ports {sec[3]}]
set_load -pin_load 0.05 [get_ports {sec[2]}]
set_load -pin_load 0.05 [get_ports {sec[1]}]
set_load -pin_load 0.05 [get_ports {sec[0]}]
set_load -pin_load 0.05 [get_ports {alarm_hour[4]}]
set_load -pin_load 0.05 [get_ports {alarm_hour[3]}]
set_load -pin_load 0.05 [get_ports {alarm_hour[2]}]
set_load -pin_load 0.05 [get_ports {alarm_hour[1]}]
set_load -pin_load 0.05 [get_ports {alarm_hour[0]}]
set_load -pin_load 0.05 [get_ports {alarm_min[5]}]
set_load -pin_load 0.05 [get_ports {alarm_min[4]}]
set_load -pin_load 0.05 [get_ports {alarm_min[3]}]
set_load -pin_load 0.05 [get_ports {alarm_min[2]}]
set_load -pin_load 0.05 [get_ports {alarm_min[1]}]
set_load -pin_load 0.05 [get_ports {alarm_min[0]}]
set_load -pin_load 0.05 [get_ports {alarm_sec[5]}]
set_load -pin_load 0.05 [get_ports {alarm_sec[4]}]
set_load -pin_load 0.05 [get_ports {alarm_sec[3]}]
set_load -pin_load 0.05 [get_ports {alarm_sec[2]}]
set_load -pin_load 0.05 [get_ports {alarm_sec[1]}]
set_load -pin_load 0.05 [get_ports {alarm_sec[0]}]
set_load -pin_load 0.05 [get_ports alarm_on]
set_false_path -from [get_ports reset]
set_clock_gating_check -setup 0.0 
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports reset]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports alarm_set]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {set_hour[4]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {set_hour[3]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {set_hour[2]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {set_hour[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {set_hour[0]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {set_min[5]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {set_min[4]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {set_min[3]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {set_min[2]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {set_min[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {set_min[0]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {set_sec[5]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {set_sec[4]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {set_sec[3]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {set_sec[2]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {set_sec[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {set_sec[0]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {hour[4]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {hour[3]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {hour[2]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {hour[1]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {hour[0]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {min[5]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {min[4]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {min[3]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {min[2]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {min[1]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {min[0]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {sec[5]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {sec[4]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {sec[3]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {sec[2]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {sec[1]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {sec[0]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {alarm_hour[4]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {alarm_hour[3]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {alarm_hour[2]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {alarm_hour[1]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {alarm_hour[0]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {alarm_min[5]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {alarm_min[4]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {alarm_min[3]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {alarm_min[2]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {alarm_min[1]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {alarm_min[0]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {alarm_sec[5]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {alarm_sec[4]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {alarm_sec[3]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {alarm_sec[2]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {alarm_sec[1]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports {alarm_sec[0]}]
set_output_delay -clock [get_clocks clk] -add_delay 2.0 [get_ports alarm_on]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports reset]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports alarm_set]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {set_hour[4]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {set_hour[3]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {set_hour[2]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {set_hour[1]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {set_hour[0]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {set_min[5]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {set_min[4]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {set_min[3]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {set_min[2]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {set_min[1]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {set_min[0]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {set_sec[5]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {set_sec[4]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {set_sec[3]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {set_sec[2]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {set_sec[1]}]
set_driving_cell -lib_cell INVX1 -library slow -pin "Y" [get_ports {set_sec[0]}]
set_wire_load_mode "enclosed"
set_clock_uncertainty -setup 0.2 [get_clocks clk]
set_clock_uncertainty -hold 0.2 [get_clocks clk]
